fiddle with feedgen

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
 
       - name: Build
         shell: powershell
@@ -57,7 +59,7 @@ jobs:
 
       - name: Build VSIX
         shell: powershell
-        run: Scripts\Build.ps1 -ci -build -updateVsixVersion -config Release
+        run: Scripts\Build.ps1 -ci -build -config Release
 
       - name: Upload VSIX Artifacts
         uses: actions/upload-artifact@v4
@@ -77,6 +79,24 @@ jobs:
           mkdir Binaries/ReleaseStaging
           mv Binaries/Release/2022/VsVim.vsix Binaries/ReleaseStaging/VsVim_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
           mv Binaries/Release/2019/VsVim.vsix Binaries/ReleaseStaging/VsVim2019_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
+
+      - name: Build VSIX feed
+        shell: powershell
+        run: |
+          $zipName = "PrivateGalleryCreator.zip"
+         Invoke-WebRequest -Uri https://github.com/madskristensen/PrivateGalleryCreator/releases/download/1.0.64/PrivateGalleryCreator.zip -OutFile $zipName
+         $zipHash = (Get-FileHash $zipName).Hash -ne "ha"
+         $expectedZipHash = "B410F7C9B93D319F5B7791687DEDA08378955AE45B7B5BD7EFC65D937FC160CA"
+         if ($zipHash -ne $expectedZipHash) {
+           Write-Error "$zipName integrity check failed; expected $expectedZipHash, got $zipHash"
+           exit 1
+         }
+
+         Expand-Archive PrivateGalleryCreator.zip -DestinationPath .
+         $tool = Resolve-Path ./PrivateGalleryCreator.exe
+         pushd Binaries/ReleaseStaging
+         & $tool
+         cat feed.xml
 
       - name: Create VS extension release
         uses: softprops/action-gh-release@v1
