Publish package feed as a release artifact, derive version numbers from git history

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,11 +15,18 @@ on:
 
 jobs:
   windows-build:
-    name: Windows Build and Test
+    name: Debug build
     runs-on: windows-2022
+    outputs:
+      tag_name: ${{ steps.tag_name.outputs.tag }}
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
+
+      - uses: dotnet/nbgv@master
+        id: nbgv
 
       - name: Build
         shell: powershell
@@ -35,6 +42,7 @@ jobs:
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
+        if: always()
         with:
           name: Logs
           path: Binaries\Logs
@@ -44,15 +52,32 @@ jobs:
   #   - An Azure DevOps artifact for easy download / use on PR or CI
   #   - The Open VSIX gallery during CI
   windows-publish:
-    name: Publish VSIX
+    name: Release build
     runs-on: windows-2022
+    if: ${{ success() && github.ref == 'refs/heads/master' }}
+    # if: ${{ startsWith(github.ref, 'refs/tags') && contains(github.ref, 'vsix') }}
+    needs:
+      - windows-build
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
+
+      - uses: dotnet/nbgv@master
+        id: nbgv
 
       - name: Build VSIX
         shell: powershell
-        run: Scripts\Build.ps1 -ci -build -updateVsixVersion -config Release
+        run: Scripts\Build.ps1 -ci -build -config Release
+
+      - name: Test
+        shell: powershell
+        run: Scripts\Build.ps1 -ci -config Release -test
+
+      - name: Test Extra
+        shell: powershell
+        run: Scripts\Build.ps1 -ci -config Release -testExtra
 
       - name: Upload VSIX Artifacts
         uses: actions/upload-artifact@v4
@@ -60,10 +85,76 @@ jobs:
           name: Vsix
           path: Binaries\Deploy
 
-      - name: Publish VSIX to Open VSIX Gallery
+        # The vsix is currently not listed on the Open VSIX Gallery: #3002
+      # - name: Publish VSIX to Open VSIX Gallery
+      #   shell: powershell
+      #   run: Scripts\Build.ps1 -ci -uploadVsix -config Release
+      #   if: ${{ success() && github.ref == 'refs/heads/master' }}
+
+      - name: Prepare VSIXes for release
         shell: powershell
-        run: Scripts\Build.ps1 -ci -uploadVsix -config Release
+        run: |
+          mkdir Binaries/ReleaseStaging
+          mv Binaries/Deploy/Release/2022/VsVim.vsix Binaries/ReleaseStaging/VsVim_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
+          mv Binaries/Deploy/Release/2019/VsVim.vsix Binaries/ReleaseStaging/VsVim2019_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
+
+      - id: tag_name
+        name: Compose tag name
+        shell: powershell
+        run: |
+          $commitDate = "${{ steps.nbgv.outputs.GitCommitDate }}"
+          $commitDate = [DateTime]::parse($commitDate)
+          $commitDate = $commitDate.ToString("yyyyMMdd")
+          $simpleVersion = "${{ steps.nbgv.outputs.SimpleVersion }}"
+          $tag = "ci-$commitDate-$simpleVersion-vsix"
+          echo "Tag: $tag"
+          echo "tag=$tag`n" >> $env:GITHUB_OUTPUT
         if: ${{ success() && github.ref == 'refs/heads/master' }}
+      - name: Create CI release tag
+        run: |
+          echo "creating tag: ${{ steps.tag_name.outputs.tag }}"
+          git tag ${{ steps.tag_name.outputs.tag }}
+          git push origin ${{ steps.tag_name.outputs.tag }}
+        # if: ${{ success() && github.ref == 'refs/heads/master' }}
+
+      - name: Build VSIX feed
+        shell: powershell
+        run: |
+          $zipName = "PrivateGalleryCreator.zip"
+          Invoke-WebRequest -Uri https://github.com/madskristensen/PrivateGalleryCreator/releases/download/1.0.64/PrivateGalleryCreator.zip -OutFile $zipName
+          $zipHash = (Get-FileHash $zipName).Hash
+          $expectedZipHash = "B410F7C9B93D319F5B7791687DEDA08378955AE45B7B5BD7EFC65D937FC160CA"
+          if ($zipHash -ne $expectedZipHash) {
+            Write-Error "$zipName integrity check failed; expected $expectedZipHash, got $zipHash"
+            exit 1
+          }
+ 
+          Expand-Archive PrivateGalleryCreator.zip -DestinationPath .
+          $tool = Resolve-Path ./PrivateGalleryCreator.exe
+          pushd Binaries/ReleaseStaging
+          $tag = "${{ steps.tag_name.outputs.tag }}"
+          $ghRepo = "${{ github.repository }}"
+          & $tool --input=$(pwd) --source="https://github.com/$ghRepo/releases/download/$tag/" -t
+          cat feed.xml
+        # if: ${{ success() && startsWith(github.ref, 'refs/tags') && contains(github.ref, 'vsix') }}
+
+      - name: Create VS extension release
+        uses: softprops/action-gh-release@v1
+        id: vsix_release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+        with:
+          name: 'VSVim ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}'
+          tag_name: '${{ steps.tag_name.outputs.tag }}'
+          draft: false
+          generate_release_notes: true
+          fail_on_unmatched_files: true
+          files: |
+            Binaries/ReleaseStaging/VsVim_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
+            Binaries/ReleaseStaging/VsVim2019_${{ steps.nbgv.outputs.AssemblyFileVersion }}.vsix
+            Binaries/ReleaseStaging/feed.xml
+
+
 
   macos-build:
     name: MacOS Build and Publish
